# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedonepayobject',
            name='transaction',
            field=models.CharField(db_index=True, default='None', max_length=190),
        ),
    ]
